name: Build ES3C35P Board

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.5.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Build Firmware for ES3C35P
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build -DBOARD=lcdwiki-es3c35p

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi-es3c35p-firmware
          path: build/*.bin
